# Generated by Django 5.2.8 on 2025-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, help_text='Primary subject/course', max_length=100, null=True),
        ),
    ]
